import type { FieldSpec } from './types';

/**
 * ISO 8583:1987 data element definitions, 1–128.
 *
 * This is the layout used by most acquiring and switch implementations.
 * Individual schemes and processors override some of the reserved ranges
 * (DE 60–63, DE 112–127) with their own private-use fields; where that is
 * common the description notes it.
 */
export const FIELD_SPECS: Record<number, FieldSpec> = {
  1: { de: 1, name: 'Secondary bitmap', content: 'b', length: 16, lengthType: 'fixed', description: 'Presence map for DE 65–128. Read from the bitmap itself, not the data stream.' },
  2: { de: 2, name: 'Primary account number (PAN)', content: 'n', length: 19, lengthType: 'LLVAR', description: 'The card number.', sensitive: true },
  3: { de: 3, name: 'Processing code', content: 'n', length: 6, lengthType: 'fixed', description: 'Transaction type + from-account + to-account, two digits each.' },
  4: { de: 4, name: 'Amount, transaction', content: 'n', length: 12, lengthType: 'fixed', description: 'Amount in the transaction currency, minor units, no decimal point.' },
  5: { de: 5, name: 'Amount, settlement', content: 'n', length: 12, lengthType: 'fixed', description: 'Amount in the acquirer settlement currency.' },
  6: { de: 6, name: 'Amount, cardholder billing', content: 'n', length: 12, lengthType: 'fixed', description: 'Amount in the currency the cardholder is billed in.' },
  7: { de: 7, name: 'Transmission date and time', content: 'n', length: 10, lengthType: 'fixed', description: 'MMDDhhmmss, UTC, set by the sender.' },
  8: { de: 8, name: 'Amount, cardholder billing fee', content: 'n', length: 8, lengthType: 'fixed' },
  9: { de: 9, name: 'Conversion rate, settlement', content: 'n', length: 8, lengthType: 'fixed', description: 'First digit is the decimal position.' },
  10: { de: 10, name: 'Conversion rate, cardholder billing', content: 'n', length: 8, lengthType: 'fixed' },
  11: { de: 11, name: 'System trace audit number (STAN)', content: 'n', length: 6, lengthType: 'fixed', description: 'Sender-assigned number that links a request to its response.' },
  12: { de: 12, name: 'Time, local transaction', content: 'n', length: 6, lengthType: 'fixed', description: 'hhmmss in the terminal local time.' },
  13: { de: 13, name: 'Date, local transaction', content: 'n', length: 4, lengthType: 'fixed', description: 'MMDD in the terminal local time.' },
  14: { de: 14, name: 'Date, expiration', content: 'n', length: 4, lengthType: 'fixed', description: 'YYMM card expiry.', sensitive: true },
  15: { de: 15, name: 'Date, settlement', content: 'n', length: 4, lengthType: 'fixed', description: 'MMDD — the settlement date the transaction falls into.' },
  16: { de: 16, name: 'Date, conversion', content: 'n', length: 4, lengthType: 'fixed' },
  17: { de: 17, name: 'Date, capture', content: 'n', length: 4, lengthType: 'fixed' },
  18: { de: 18, name: 'Merchant type (MCC)', content: 'n', length: 4, lengthType: 'fixed', description: 'Merchant category code.' },
  19: { de: 19, name: 'Acquiring institution country code', content: 'n', length: 3, lengthType: 'fixed' },
  20: { de: 20, name: 'PAN extended country code', content: 'n', length: 3, lengthType: 'fixed' },
  21: { de: 21, name: 'Forwarding institution country code', content: 'n', length: 3, lengthType: 'fixed' },
  22: { de: 22, name: 'POS entry mode', content: 'n', length: 3, lengthType: 'fixed', description: 'How the card was read, plus the PIN entry capability of the terminal.' },
  23: { de: 23, name: 'Card sequence number', content: 'n', length: 3, lengthType: 'fixed', description: 'Distinguishes cards sharing one PAN.' },
  24: { de: 24, name: 'Network international identifier (NII)', content: 'n', length: 3, lengthType: 'fixed', description: 'Function code in the 1993 version.' },
  25: { de: 25, name: 'POS condition code', content: 'n', length: 2, lengthType: 'fixed', description: 'Circumstances of the transaction, e.g. cardholder present, mail order.' },
  26: { de: 26, name: 'POS PIN capture code', content: 'n', length: 2, lengthType: 'fixed' },
  27: { de: 27, name: 'Authorization identification response length', content: 'n', length: 1, lengthType: 'fixed' },
  28: { de: 28, name: 'Amount, transaction fee', content: 'x+n', length: 9, lengthType: 'fixed', description: 'C or D indicator followed by 8 digits.' },
  29: { de: 29, name: 'Amount, settlement fee', content: 'x+n', length: 9, lengthType: 'fixed' },
  30: { de: 30, name: 'Amount, transaction processing fee', content: 'x+n', length: 9, lengthType: 'fixed' },
  31: { de: 31, name: 'Amount, settlement processing fee', content: 'x+n', length: 9, lengthType: 'fixed' },
  32: { de: 32, name: 'Acquiring institution identification code', content: 'n', length: 11, lengthType: 'LLVAR', description: 'Identifies the acquirer to the scheme.' },
  33: { de: 33, name: 'Forwarding institution identification code', content: 'n', length: 11, lengthType: 'LLVAR' },
  34: { de: 34, name: 'PAN extended', content: 'ans', length: 28, lengthType: 'LLVAR', sensitive: true },
  35: { de: 35, name: 'Track 2 data', content: 'z', length: 37, lengthType: 'LLVAR', description: 'PAN, separator, expiry, service code and discretionary data as read from the stripe or chip.', sensitive: true },
  36: { de: 36, name: 'Track 3 data', content: 'z', length: 104, lengthType: 'LLLVAR', sensitive: true },
  37: { de: 37, name: 'Retrieval reference number (RRN)', content: 'an', length: 12, lengthType: 'fixed', description: 'The reference used to find this transaction later — the key you reconcile on.' },
  38: { de: 38, name: 'Authorization identification response', content: 'an', length: 6, lengthType: 'fixed', description: 'The approval code returned by the issuer.' },
  39: { de: 39, name: 'Response code', content: 'an', length: 2, lengthType: 'fixed', description: 'Outcome of the transaction. 00 is approved; everything else is not.' },
  40: { de: 40, name: 'Service restriction code', content: 'an', length: 3, lengthType: 'fixed' },
  41: { de: 41, name: 'Card acceptor terminal identification', content: 'ans', length: 8, lengthType: 'fixed', description: 'Terminal ID (TID).' },
  42: { de: 42, name: 'Card acceptor identification code', content: 'ans', length: 15, lengthType: 'fixed', description: 'Merchant ID (MID).' },
  43: { de: 43, name: 'Card acceptor name/location', content: 'ans', length: 40, lengthType: 'fixed', description: 'Merchant name, city and country — what appears on the cardholder statement.' },
  44: { de: 44, name: 'Additional response data', content: 'an', length: 25, lengthType: 'LLVAR' },
  45: { de: 45, name: 'Track 1 data', content: 'an', length: 76, lengthType: 'LLVAR', sensitive: true },
  46: { de: 46, name: 'Additional data — ISO', content: 'an', length: 999, lengthType: 'LLLVAR' },
  47: { de: 47, name: 'Additional data — national', content: 'an', length: 999, lengthType: 'LLLVAR' },
  48: { de: 48, name: 'Additional data — private', content: 'an', length: 999, lengthType: 'LLLVAR', description: 'Commonly used by processors for their own sub-field structures.' },
  49: { de: 49, name: 'Currency code, transaction', content: 'an', length: 3, lengthType: 'fixed', description: 'ISO 4217 numeric currency code.' },
  50: { de: 50, name: 'Currency code, settlement', content: 'an', length: 3, lengthType: 'fixed' },
  51: { de: 51, name: 'Currency code, cardholder billing', content: 'an', length: 3, lengthType: 'fixed' },
  52: { de: 52, name: 'PIN data', content: 'b', length: 16, lengthType: 'fixed', description: 'Encrypted PIN block, 8 bytes.', sensitive: true },
  53: { de: 53, name: 'Security related control information', content: 'n', length: 16, lengthType: 'fixed' },
  54: { de: 54, name: 'Additional amounts', content: 'an', length: 120, lengthType: 'LLLVAR', description: 'Repeating 20-character groups — account type, amount type, currency, amount.' },
  55: { de: 55, name: 'ICC data (EMV)', content: 'b', length: 999, lengthType: 'LLLVAR', description: 'BER-TLV chip data: cryptogram, TVR, ATC, issuer application data and more.' },
  56: { de: 56, name: 'Reserved ISO', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  57: { de: 57, name: 'Reserved national', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  58: { de: 58, name: 'Reserved national', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  59: { de: 59, name: 'Reserved national', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  60: { de: 60, name: 'Reserved private', content: 'ans', length: 999, lengthType: 'LLLVAR', description: 'Processor-specific. Often carries terminal or batch information.' },
  61: { de: 61, name: 'Reserved private', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  62: { de: 62, name: 'Reserved private', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  63: { de: 63, name: 'Reserved private', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  64: { de: 64, name: 'Message authentication code (MAC)', content: 'b', length: 16, lengthType: 'fixed', description: 'Integrity check over the message.' },
  65: { de: 65, name: 'Extended bitmap indicator', content: 'b', length: 16, lengthType: 'fixed' },
  66: { de: 66, name: 'Settlement code', content: 'n', length: 1, lengthType: 'fixed' },
  67: { de: 67, name: 'Extended payment code', content: 'n', length: 2, lengthType: 'fixed' },
  68: { de: 68, name: 'Receiving institution country code', content: 'n', length: 3, lengthType: 'fixed' },
  69: { de: 69, name: 'Settlement institution country code', content: 'n', length: 3, lengthType: 'fixed' },
  70: { de: 70, name: 'Network management information code', content: 'n', length: 3, lengthType: 'fixed', description: '001 sign-on, 002 sign-off, 301 echo test.' },
  71: { de: 71, name: 'Message number', content: 'n', length: 4, lengthType: 'fixed' },
  72: { de: 72, name: 'Message number, last', content: 'n', length: 4, lengthType: 'fixed' },
  73: { de: 73, name: 'Date, action', content: 'n', length: 6, lengthType: 'fixed', description: 'YYMMDD.' },
  74: { de: 74, name: 'Credits, number', content: 'n', length: 10, lengthType: 'fixed', description: 'Reconciliation totals field.' },
  75: { de: 75, name: 'Credits, reversal number', content: 'n', length: 10, lengthType: 'fixed' },
  76: { de: 76, name: 'Debits, number', content: 'n', length: 10, lengthType: 'fixed' },
  77: { de: 77, name: 'Debits, reversal number', content: 'n', length: 10, lengthType: 'fixed' },
  78: { de: 78, name: 'Transfer, number', content: 'n', length: 10, lengthType: 'fixed' },
  79: { de: 79, name: 'Transfer, reversal number', content: 'n', length: 10, lengthType: 'fixed' },
  80: { de: 80, name: 'Inquiries, number', content: 'n', length: 10, lengthType: 'fixed' },
  81: { de: 81, name: 'Authorizations, number', content: 'n', length: 10, lengthType: 'fixed' },
  82: { de: 82, name: 'Credits, processing fee amount', content: 'n', length: 12, lengthType: 'fixed' },
  83: { de: 83, name: 'Credits, transaction fee amount', content: 'n', length: 12, lengthType: 'fixed' },
  84: { de: 84, name: 'Debits, processing fee amount', content: 'n', length: 12, lengthType: 'fixed' },
  85: { de: 85, name: 'Debits, transaction fee amount', content: 'n', length: 12, lengthType: 'fixed' },
  86: { de: 86, name: 'Credits, amount', content: 'n', length: 16, lengthType: 'fixed' },
  87: { de: 87, name: 'Credits, reversal amount', content: 'n', length: 16, lengthType: 'fixed' },
  88: { de: 88, name: 'Debits, amount', content: 'n', length: 16, lengthType: 'fixed' },
  89: { de: 89, name: 'Debits, reversal amount', content: 'n', length: 16, lengthType: 'fixed' },
  90: { de: 90, name: 'Original data elements', content: 'n', length: 42, lengthType: 'fixed', description: 'Identifies the transaction being reversed: original MTI, STAN, date/time, acquirer ID.' },
  91: { de: 91, name: 'File update code', content: 'an', length: 1, lengthType: 'fixed' },
  92: { de: 92, name: 'File security code', content: 'an', length: 2, lengthType: 'fixed' },
  93: { de: 93, name: 'Response indicator', content: 'an', length: 5, lengthType: 'fixed' },
  94: { de: 94, name: 'Service indicator', content: 'an', length: 7, lengthType: 'fixed' },
  95: { de: 95, name: 'Replacement amounts', content: 'an', length: 42, lengthType: 'fixed', description: 'Corrected amounts on a partial reversal.' },
  96: { de: 96, name: 'Message security code', content: 'b', length: 16, lengthType: 'fixed' },
  97: { de: 97, name: 'Amount, net settlement', content: 'x+n', length: 17, lengthType: 'fixed' },
  98: { de: 98, name: 'Payee', content: 'ans', length: 25, lengthType: 'fixed' },
  99: { de: 99, name: 'Settlement institution identification code', content: 'n', length: 11, lengthType: 'LLVAR' },
  100: { de: 100, name: 'Receiving institution identification code', content: 'n', length: 11, lengthType: 'LLVAR' },
  101: { de: 101, name: 'File name', content: 'ans', length: 17, lengthType: 'LLVAR' },
  102: { de: 102, name: 'Account identification 1', content: 'ans', length: 28, lengthType: 'LLVAR', description: 'The "from" account.', sensitive: true },
  103: { de: 103, name: 'Account identification 2', content: 'ans', length: 28, lengthType: 'LLVAR', description: 'The "to" account.', sensitive: true },
  104: { de: 104, name: 'Transaction description', content: 'ans', length: 100, lengthType: 'LLLVAR' },
  105: { de: 105, name: 'Reserved ISO use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  106: { de: 106, name: 'Reserved ISO use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  107: { de: 107, name: 'Reserved ISO use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  108: { de: 108, name: 'Reserved ISO use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  109: { de: 109, name: 'Reserved ISO use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  110: { de: 110, name: 'Reserved ISO use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  111: { de: 111, name: 'Reserved ISO use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  112: { de: 112, name: 'Reserved national use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  113: { de: 113, name: 'Reserved national use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  114: { de: 114, name: 'Reserved national use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  115: { de: 115, name: 'Reserved national use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  116: { de: 116, name: 'Reserved national use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  117: { de: 117, name: 'Reserved national use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  118: { de: 118, name: 'Reserved national use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  119: { de: 119, name: 'Reserved national use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  120: { de: 120, name: 'Reserved private use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  121: { de: 121, name: 'Reserved private use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  122: { de: 122, name: 'Reserved private use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  123: { de: 123, name: 'Reserved private use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  124: { de: 124, name: 'Reserved private use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  125: { de: 125, name: 'Reserved private use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  126: { de: 126, name: 'Reserved private use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  127: { de: 127, name: 'Reserved private use', content: 'ans', length: 999, lengthType: 'LLLVAR' },
  128: { de: 128, name: 'Message authentication code (MAC)', content: 'b', length: 16, lengthType: 'fixed' },
};

/** Number of characters the length prefix occupies for a given length type. */
export function prefixLength(spec: FieldSpec): number {
  switch (spec.lengthType) {
    case 'LLVAR':
      return 2;
    case 'LLLVAR':
      return 3;
    default:
      return 0;
  }
}

export function getSpec(de: number): FieldSpec | undefined {
  return FIELD_SPECS[de];
}
